--- 
abstract: Install everything Perl::Critic.
author: Elliot Shank <perl@galumph.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-Perl-Critic
no_index: 
  directory: 
    - inc
    - t
requires: 
  Perl::Critic: 1.061
  Perl::Critic::Bangs: 0
  Perl::Critic::Lax: 0
  Perl::Critic::More: 0
  Perl::Critic::StricterSubs: 0
  Perl::Critic::Swift: 0
  Perl::Critic::Tics: 0
  Test::Perl::Critic: 1.01
  Test::Perl::Critic::Progressive: 0.02
  criticism: 1.01
  perl: 5.6.1
version: v1.002
